

import model.UberDetails;
import model.UberDetailsHistory;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yashn
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     * 
     */
   UberDetailsHistory history;
    public SearchJPanel(UberDetailsHistory history) {
        
        initComponents();
        this.history=history;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_First_availablecar_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_enter_serial_search = new javax.swing.JTextField();
        btn_currently_available_or_not_search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_enter_car_name_search1 = new javax.swing.JTextField();
        btn_man_year_search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_enter_max_seat_search = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_enter_min_seat_search = new javax.swing.JTextField();
        btn_serial_search = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_enter_car_madeBy_search = new javax.swing.JTextField();
        btn_minmax_seat_search1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_enter_model_search = new javax.swing.JTextField();
        btn_model_search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_manByUber_search = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btn_city_search = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_enter_city_name_search = new javax.swing.JTextField();
        btn_table_UpdatedOn_search1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btn_expired_certi_search = new javax.swing.JButton();
        txt_enter_man_year_search = new javax.swing.JTextField();
        btn_car_made_By_search = new javax.swing.JButton();
        lblLastUpdated = new javax.swing.JLabel();

        tblView.setBackground(new java.awt.Color(0, 0, 0));
        tblView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblView.setForeground(new java.awt.Color(255, 255, 255));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car_Name", "Man_Company", "Location", "Availabilility", "Min_Seats", "Max_Seats", "Serial_No", "Model_No", "Mainte_Ex_Expiry", "Available Time", "Man_Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblView.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblView);

        jLabel1.setText("Search Data");

        jLabel2.setText("First Available Car:");

        btn_First_availablecar_search.setText("Search");
        btn_First_availablecar_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_First_availablecar_searchActionPerformed(evt);
            }
        });

        jLabel3.setText("How many cars are currently available and not available:");

        jLabel4.setText("List Cars made by :");

        txt_enter_serial_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_serial_searchActionPerformed(evt);
            }
        });

        btn_currently_available_or_not_search.setText("Search");

        jLabel5.setText("Car manufactured in year:");

        txt_enter_car_name_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_car_name_search1ActionPerformed(evt);
            }
        });

        btn_man_year_search.setText("Search");

        jLabel6.setText("Min & Max Seats:");

        txt_enter_max_seat_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_max_seat_searchActionPerformed(evt);
            }
        });

        jLabel7.setText("Min:");

        jLabel8.setText("Max:");

        txt_enter_min_seat_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_min_seat_searchActionPerformed(evt);
            }
        });

        btn_serial_search.setText("Search");
        btn_serial_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serial_searchActionPerformed(evt);
            }
        });

        jLabel9.setText("find car with serial No:");

        txt_enter_car_madeBy_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_car_madeBy_searchActionPerformed(evt);
            }
        });

        btn_minmax_seat_search1.setText("Search");
        btn_minmax_seat_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minmax_seat_search1ActionPerformed(evt);
            }
        });

        jLabel10.setText("find car with model No:");

        txt_enter_model_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_model_searchActionPerformed(evt);
            }
        });

        btn_model_search.setText("Search");
        btn_model_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_model_searchActionPerformed(evt);
            }
        });

        jLabel11.setText("car manufac. by uber :");

        btn_manByUber_search.setText("Search");
        btn_manByUber_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manByUber_searchActionPerformed(evt);
            }
        });

        jLabel12.setText("Seach car by city:");

        btn_city_search.setText("Search");
        btn_city_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_city_searchActionPerformed(evt);
            }
        });

        jLabel13.setText("Last time table updated on:");

        txt_enter_city_name_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_city_name_searchActionPerformed(evt);
            }
        });

        btn_table_UpdatedOn_search1.setText("Search");
        btn_table_UpdatedOn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_table_UpdatedOn_search1ActionPerformed(evt);
            }
        });

        jLabel14.setText("List of car with expired maitenance caerti:");

        btn_expired_certi_search.setText("Search");
        btn_expired_certi_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expired_certi_searchActionPerformed(evt);
            }
        });

        txt_enter_man_year_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_man_year_searchActionPerformed(evt);
            }
        });

        btn_car_made_By_search.setText("Search");
        btn_car_made_By_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_made_By_searchActionPerformed(evt);
            }
        });

        lblLastUpdated.setText("     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_enter_car_madeBy_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_car_made_By_search)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71)
                                .addComponent(btn_First_availablecar_search))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_enter_min_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_enter_max_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_minmax_seat_search1)
                                    .addComponent(btn_expired_certi_search)
                                    .addComponent(btn_currently_available_or_not_search))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_enter_serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_serial_search))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_enter_man_year_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_man_year_search))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_enter_model_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_model_search))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_enter_car_name_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(137, 137, 137)
                                                .addComponent(lblLastUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_table_UpdatedOn_search1)
                                            .addComponent(btn_manByUber_search)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(txt_enter_city_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_city_search)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_First_availablecar_search)
                    .addComponent(jLabel5)
                    .addComponent(txt_enter_man_year_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_man_year_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_currently_available_or_not_search)
                            .addComponent(jLabel9)
                            .addComponent(txt_enter_serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_serial_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_expired_certi_search)
                            .addComponent(jLabel10)
                            .addComponent(txt_enter_model_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_model_search))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txt_enter_min_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_enter_max_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_car_made_By_search)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_enter_car_madeBy_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(lblLastUpdated))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_minmax_seat_search1)
                            .addComponent(jLabel11)
                            .addComponent(txt_enter_car_name_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_manByUber_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_table_UpdatedOn_search1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_enter_city_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_city_search))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_enter_serial_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_serial_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_serial_searchActionPerformed

    private void txt_enter_car_name_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_car_name_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_car_name_search1ActionPerformed

    private void txt_enter_max_seat_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_max_seat_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_max_seat_searchActionPerformed

    private void txt_enter_min_seat_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_min_seat_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_min_seat_searchActionPerformed

    private void btn_serial_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serial_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_serial_searchActionPerformed

    private void txt_enter_car_madeBy_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_car_madeBy_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_car_madeBy_searchActionPerformed

    private void btn_minmax_seat_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minmax_seat_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_minmax_seat_search1ActionPerformed

    private void txt_enter_model_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_model_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_model_searchActionPerformed

    private void btn_model_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_model_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_model_searchActionPerformed

    private void btn_manByUber_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manByUber_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_manByUber_searchActionPerformed

    private void btn_city_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_city_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_city_searchActionPerformed

    private void txt_enter_city_name_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_city_name_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_city_name_searchActionPerformed

    private void btn_table_UpdatedOn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_table_UpdatedOn_search1ActionPerformed
        // TODO add your handling code here:
        
        // Get Manufaturer
        lblLastUpdated.setText("Today");
    }//GEN-LAST:event_btn_table_UpdatedOn_search1ActionPerformed

    private void btn_expired_certi_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expired_certi_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_expired_certi_searchActionPerformed

    private void txt_enter_man_year_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_man_year_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_man_year_searchActionPerformed

    private void btn_First_availablecar_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_First_availablecar_searchActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_btn_First_availablecar_searchActionPerformed

    private void btn_car_made_By_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_made_By_searchActionPerformed
        // TODO add your handling code here:
        
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();
        
        String filterMan = txt_enter_car_madeBy_search.getText();
        
               
        for(UberDetails car: allCars){
        
            
            //Match the car.getManufacturer with filterMan
            
            if(car.getManufacture().equals(filterMan)){
                searchList.add(car);
            }
        }
        
        
        populateTableByList2(searchList);
    }//GEN-LAST:event_btn_car_made_By_searchActionPerformed

    public void populateTableByList2(ArrayList<UberDetails> list) {
        
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        model.setRowCount(0);
        
        for(UberDetails cs :list){
            Object[] row=new Object[11];
            
            row[0]=cs;//.getCar_name();
            row[1]=cs.getCarname();
            row[2]=cs.getModel();
            row[3]=cs.getManuyear();
            row[4]=cs.getSerialno();
            row[5]=cs.isManucerti();//check whether it should be get or is(as get is not available)
            row[6]=cs.isAvailable();
            row[7]=cs.getLocation();
            row[8]=cs.getMinseats();
            row[9]=cs.getMaxseats();
            row[10]=cs.getTime();
            
            model.addRow(row);
            
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First_availablecar_search;
    private javax.swing.JButton btn_car_made_By_search;
    private javax.swing.JButton btn_city_search;
    private javax.swing.JButton btn_currently_available_or_not_search;
    private javax.swing.JButton btn_expired_certi_search;
    private javax.swing.JButton btn_manByUber_search;
    private javax.swing.JButton btn_man_year_search;
    private javax.swing.JButton btn_minmax_seat_search1;
    private javax.swing.JButton btn_model_search;
    private javax.swing.JButton btn_serial_search;
    private javax.swing.JButton btn_table_UpdatedOn_search1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txt_enter_car_madeBy_search;
    private javax.swing.JTextField txt_enter_car_name_search1;
    private javax.swing.JTextField txt_enter_city_name_search;
    private javax.swing.JTextField txt_enter_man_year_search;
    private javax.swing.JTextField txt_enter_max_seat_search;
    private javax.swing.JTextField txt_enter_min_seat_search;
    private javax.swing.JTextField txt_enter_model_search;
    private javax.swing.JTextField txt_enter_serial_search;
    // End of variables declaration//GEN-END:variables
}
