/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import javax.swing.JOptionPane;
import model.UberDetails;
import model.UberDetailsHistory;

/**
 *
 * @author kohli
 */
public class CreateJPanel extends javax.swing.JPanel {

    
    UberDetailsHistory history;
    public CreateJPanel(UberDetailsHistory history) {
        initComponents();
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        txtCardetails = new javax.swing.JPanel();
        lblManufacture = new javax.swing.JLabel();
        txtManufacture = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();
        lblManuyear = new javax.swing.JLabel();
        txtCarname = new javax.swing.JTextField();
        lblCarname = new javax.swing.JLabel();
        lblSerialno = new javax.swing.JLabel();
        txtManuyear1 = new javax.swing.JTextField();
        txtVehicleavail = new javax.swing.JPanel();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblAvailabletime = new javax.swing.JLabel();
        txtMinseats = new javax.swing.JTextField();
        lblMinseats = new javax.swing.JLabel();
        lblAvailability = new javax.swing.JLabel();
        txtAvailabletime = new javax.swing.JTextField();
        chkbxAvailYes = new javax.swing.JCheckBox();
        txtMaintenacevehicle = new javax.swing.JPanel();
        lblExpired = new javax.swing.JLabel();
        chkbxlExpiredYes = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(102, 102, 102));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Create Vehicle Details ");

        txtCardetails.setBackground(new java.awt.Color(0, 0, 0));
        txtCardetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 153)));
        txtCardetails.setForeground(new java.awt.Color(255, 255, 255));

        lblManufacture.setForeground(new java.awt.Color(255, 255, 255));
        lblManufacture.setText("Manufacture:");

        txtManufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureActionPerformed(evt);
            }
        });
        txtManufacture.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtManufactureKeyPressed(evt);
            }
        });

        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");

        lblManuyear.setForeground(new java.awt.Color(255, 255, 255));
        lblManuyear.setText("Manu. Year:");
        lblManuyear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblManuyearKeyPressed(evt);
            }
        });

        txtCarname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnameActionPerformed(evt);
            }
        });
        txtCarname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarnameKeyPressed(evt);
            }
        });

        lblCarname.setForeground(new java.awt.Color(255, 255, 255));
        lblCarname.setText("Car Name:");

        lblSerialno.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialno.setText("Serial No:");

        txtManuyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManuyear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtCardetailsLayout = new javax.swing.GroupLayout(txtCardetails);
        txtCardetails.setLayout(txtCardetailsLayout);
        txtCardetailsLayout.setHorizontalGroup(
            txtCardetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCardetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblManufacture)
                .addGap(18, 18, 18)
                .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblCarname, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCarname, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lblModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblManuyear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtManuyear1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lblSerialno)
                .addGap(45, 45, 45)
                .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtCardetailsLayout.setVerticalGroup(
            txtCardetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCardetailsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(txtCardetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManuyear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCarname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblManufacture)
                    .addComponent(lblSerialno)
                    .addComponent(txtManuyear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        txtVehicleavail.setBackground(new java.awt.Color(0, 0, 0));
        txtVehicleavail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Availability Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 153)));
        txtVehicleavail.setForeground(new java.awt.Color(255, 255, 255));

        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location:");

        lblAvailabletime.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailabletime.setText("Available Time(in 24 hrs):");

        lblMinseats.setForeground(new java.awt.Color(255, 255, 255));
        lblMinseats.setText("Seats:");

        lblAvailability.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailability.setText("Availability:");

        chkbxAvailYes.setBackground(new java.awt.Color(0, 0, 0));
        chkbxAvailYes.setForeground(new java.awt.Color(255, 255, 255));
        chkbxAvailYes.setText("YES");

        javax.swing.GroupLayout txtVehicleavailLayout = new javax.swing.GroupLayout(txtVehicleavail);
        txtVehicleavail.setLayout(txtVehicleavailLayout);
        txtVehicleavailLayout.setHorizontalGroup(
            txtVehicleavailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtVehicleavailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLocation)
                .addGap(18, 18, 18)
                .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(lblMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(lblAvailability)
                .addGap(18, 18, 18)
                .addComponent(chkbxAvailYes)
                .addGap(80, 80, 80)
                .addComponent(lblAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        txtVehicleavailLayout.setVerticalGroup(
            txtVehicleavailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtVehicleavailLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(txtVehicleavailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtVehicleavailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAvailability)
                        .addComponent(chkbxAvailYes))
                    .addGroup(txtVehicleavailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLocation)
                        .addComponent(txtAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txtMaintenacevehicle.setBackground(new java.awt.Color(0, 0, 0));
        txtMaintenacevehicle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Maintenance Vehicle Certificate", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(153, 153, 153)));
        txtMaintenacevehicle.setForeground(new java.awt.Color(255, 255, 255));

        lblExpired.setForeground(new java.awt.Color(255, 255, 255));
        lblExpired.setText("Expired:");

        chkbxlExpiredYes.setBackground(new java.awt.Color(0, 0, 0));
        chkbxlExpiredYes.setForeground(new java.awt.Color(255, 255, 255));
        chkbxlExpiredYes.setText("YES");

        javax.swing.GroupLayout txtMaintenacevehicleLayout = new javax.swing.GroupLayout(txtMaintenacevehicle);
        txtMaintenacevehicle.setLayout(txtMaintenacevehicleLayout);
        txtMaintenacevehicleLayout.setHorizontalGroup(
            txtMaintenacevehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMaintenacevehicleLayout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(lblExpired)
                .addContainerGap(591, Short.MAX_VALUE))
            .addGroup(txtMaintenacevehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtMaintenacevehicleLayout.createSequentialGroup()
                    .addGap(494, 494, 494)
                    .addComponent(chkbxlExpiredYes)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );
        txtMaintenacevehicleLayout.setVerticalGroup(
            txtMaintenacevehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMaintenacevehicleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblExpired)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(txtMaintenacevehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtMaintenacevehicleLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(chkbxlExpiredYes)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Upload Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleavail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaintenacevehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCardetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(409, 409, 409)
                                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(499, 499, 499)
                        .addComponent(btnSave)
                        .addGap(154, 154, 154)
                        .addComponent(jButton1)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtCardetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(txtMaintenacevehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtVehicleavail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton1))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        txtCardetails.getAccessibleContext().setAccessibleName("Vehicle Manufacture Details");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String manufacture=txtManufacture.getText();
        String model=txtModel.getText();
       // try{
           // int manuyear=Integer.parseInt(txtManuyear1.getText());
        //}
        //catch(Exception e){
         //   JOptionPane.showMessageDialog(this,"Kindly enter valid format");
        //}
        
       // if(txtManuyear1.getText().contains("[a-zA-Z]+")){
         if(txtManuyear1.getText().equals("")){
             
       JOptionPane.showMessageDialog(null, "Enter value in Manufactureyear");  
        return;
       } 
        int manuyear=Integer.parseInt(txtManuyear1.getText());
    
       
        String serialno=txtSerialNo.getText();
        checkuniqueserialno(txtSerialNo.getText());
        
        int minseats=Integer.parseInt(txtMinseats.getText());
        //int maxseats=Integer.parseInt(txtMaxseats.getText());
        String location=txtLocation.getText();
        Double time=Double.parseDouble(txtAvailabletime.getText());
        String carname=txtCarname.getText();
        boolean available=chkbxAvailYes.isSelected();
        boolean manucerti=chkbxlExpiredYes.isSelected();
       // Date dateofupdate = new Date(); //CHECK DATA TYPE & put try & catch for integer
        Date date_of_Upadte = new Date();
        
        UberDetails ud=history.addNewCars();
        
        ud.setCarname(carname);
        ud.setManufacture(manufacture);
        ud.setModel(model);
       // ud.setMaxseats(maxseats);
        ud.setMinseats(minseats);
        ud.setManuyear(manuyear); //check for error 1 might be there
        ud.setSerialno(serialno);
        ud.setLocation(location);
        ud.setTime(time);
        //ud.setDate_of_Upadte(date_of_Upadte);
        ud.setAvailable(available);
        ud.setManucerti(manucerti);
        
        
        JOptionPane.showMessageDialog(this,"Successfully Created");
        
        txtCarname.setText("");
        txtManufacture.setText("");
        txtModel.setText("");
        txtLocation.setText("");
        txtAvailabletime.setText("");
        txtManuyear1.setText("");
        txtMinseats.setText("");
       // txtMaxseats.setText("");
        txtSerialNo.setText("");
        //txtDate.setText("");
        chkbxAvailYes.setSelected(false);
        chkbxlExpiredYes.setSelected(false);
        
        
        
        

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        history = getDataFromCSV();
//        System.out.println(history.getHistory());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtManuyear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManuyear1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtManuyear1ActionPerformed

    private void txtCarnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarnameKeyPressed
        // TODO add your handling code here:
        //namevalidation
        char c = evt.getKeyChar();
    if(Character.isDigit(c)){
        txtCarname.setEditable(false);
         JOptionPane.showMessageDialog(this,"Wrire characters only");
    }
    else{
         txtCarname.setEditable(true);
        
    }
    }//GEN-LAST:event_txtCarnameKeyPressed

    private void txtManufactureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManufactureKeyPressed
        // TODO add your handling code here:
           char m = evt.getKeyChar();
    if(Character.isDigit(m)){
      txtManufacture.setEditable(false);
      JOptionPane.showMessageDialog(this,"Wrire characters only");
    }
    else{
      txtManufacture.setEditable(true);

    }
    }//GEN-LAST:event_txtManufactureKeyPressed

    private void lblManuyearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblManuyearKeyPressed
        // TODO add your handling code here:
       
     
    }//GEN-LAST:event_lblManuyearKeyPressed

    private void txtCarnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnameActionPerformed

    private void txtManufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkbxAvailYes;
    private javax.swing.JCheckBox chkbxlExpiredYes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblAvailabletime;
    private javax.swing.JLabel lblCarname;
    private javax.swing.JLabel lblExpired;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblManufacture;
    private javax.swing.JLabel lblManuyear;
    private javax.swing.JLabel lblMinseats;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialno;
    private javax.swing.JTextField txtAvailabletime;
    private javax.swing.JPanel txtCardetails;
    private javax.swing.JTextField txtCarname;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JPanel txtMaintenacevehicle;
    private javax.swing.JTextField txtManufacture;
    private javax.swing.JTextField txtManuyear1;
    private javax.swing.JTextField txtMinseats;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JPanel txtVehicleavail;
    // End of variables declaration//GEN-END:variables

//    private UberDetailsHistory getDataFromCSV() {
//        UberDetailsHistory csvData = new UberDetailsHistory();
//        Path pathToFile = Paths.get("CarData1.csv");
//        try(BufferedReader br = Files.newBufferedReader(pathToFile,StandardCharsets.US_ASCII)){
//        String line = br.readLine();
////            System.out.println(line.length());
//            
//        while(line!= null){
////            System.out.println(line);
//        String[] attributes = line.split(",");
//            UberDetails car = addCar(attributes);
//        csvData.addNewCars(car);
////        System.out.println(csvData.getHistory().size());
//        line = br.readLine();
//        }
//        }catch(IOException ioe){
//        ioe.printStackTrace();
//}
//return csvData;
//}

//To change body of generated methods, choose Tools | Templates.

//    private UberDetails addCar(String[] attributes) {
//        UberDetails car = new UberDetails();
//car.setManufacture(attributes[0]);
//car.setCarname(attributes[1]);
//car.setModel(attributes[2]);
////car.setModel(Integer.parseInt(attributes[2]));
//car.setManuyear(Integer.parseInt(attributes[3]));
//car.setSerialno(attributes[4]);
//car.setManucerti(Boolean.parseBoolean(attributes[5]));
//car.setAvailable(Boolean.parseBoolean(attributes[6]));
//car.setLocation(attributes[7]);
//car.setMinseats(Integer.parseInt(attributes[8]));
//car.setTime(Double.parseDouble(attributes[9]));
//
//return car;
        //To change body of generated methods, choose Tools | Templates.
//    }
//}

    private boolean checkuniqueserialno(String text) {
        for(UberDetails ub :history.getHistory()){
            if(ub.getSerialno().equals(text)){
                JOptionPane.showMessageDialog(this,"Define unique serial no");
                return false;
            }  
        }
        return true;
    }
}

