/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UberDetails;
import model.UberDetailsHistory;

/**
 *
 * @author kohli
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    
     UberDetailsHistory history;
    public SearchJPanel(UberDetailsHistory history) {
        initComponents();
        this.history=history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneTable = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_table_UpdatedOn_search1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_enter_man_year_search = new javax.swing.JTextField();
        txt_enter_serial_search = new javax.swing.JTextField();
        lblLastUpdated = new javax.swing.JLabel();
        btn_man_year_search = new javax.swing.JButton();
        txt_enter_car_name_search1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_enter_model_search = new javax.swing.JTextField();
        btn_model_search = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_serial_search = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_manByUber_search = new javax.swing.JButton();
        txt_enter_city_name_search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_city_search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_enter_max_seat_search = new javax.swing.JTextField();
        btn_car_made_By_search = new javax.swing.JButton();
        btn_expired_certi_search = new javax.swing.JButton();
        btn_currently_available_or_not_search = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_First_availablecar_search = new javax.swing.JButton();
        btn_minmax_seat_search1 = new javax.swing.JButton();
        txt_enter_car_madeBy_search = new javax.swing.JTextField();
        txt_enter_min_seat_search = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_maintenanceexpired = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));

        tblView.setBackground(new java.awt.Color(153, 153, 153));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Car Name", "Model", "Manu. Year", "Serial No.", "Vehicle Maint. ", "Availability", "Location", "Seats", "Available Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneTable.setViewportView(tblView);
        if (tblView.getColumnModel().getColumnCount() > 0) {
            tblView.getColumnModel().getColumn(9).setResizable(false);
            tblView.getColumnModel().getColumn(9).setHeaderValue("Available Time");
        }

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search ");

        btn_table_UpdatedOn_search1.setText("Search");
        btn_table_UpdatedOn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_table_UpdatedOn_search1ActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last time table updated on:");

        txt_enter_man_year_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_man_year_searchActionPerformed(evt);
            }
        });

        txt_enter_serial_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_serial_searchActionPerformed(evt);
            }
        });

        lblLastUpdated.setText("     ");

        btn_man_year_search.setText("Search");
        btn_man_year_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_man_year_searchActionPerformed(evt);
            }
        });

        txt_enter_car_name_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_car_name_search1ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Car manufactured in year:");

        txt_enter_model_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_model_searchActionPerformed(evt);
            }
        });

        btn_model_search.setText("Search");
        btn_model_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_model_searchActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("find car with model No:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("find car with serial No:");

        btn_serial_search.setText("Search");
        btn_serial_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serial_searchActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("car manufac. by uber :");

        btn_manByUber_search.setText("Search");
        btn_manByUber_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manByUber_searchActionPerformed(evt);
            }
        });

        txt_enter_city_name_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_city_name_searchActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Max:");

        btn_city_search.setText("Search");
        btn_city_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_city_searchActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Min:");

        txt_enter_max_seat_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_max_seat_searchActionPerformed(evt);
            }
        });

        btn_car_made_By_search.setText("Search");
        btn_car_made_By_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_made_By_searchActionPerformed(evt);
            }
        });

        btn_expired_certi_search.setText("Search");
        btn_expired_certi_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expired_certi_searchActionPerformed(evt);
            }
        });

        btn_currently_available_or_not_search.setText("Search");
        btn_currently_available_or_not_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_currently_available_or_not_searchActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("List Cars made by :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Min & Max Seats:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Available Car:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("How many cars are currently available and not available:");

        btn_First_availablecar_search.setText("Search");
        btn_First_availablecar_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_First_availablecar_searchActionPerformed(evt);
            }
        });

        btn_minmax_seat_search1.setText("Search");
        btn_minmax_seat_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minmax_seat_search1ActionPerformed(evt);
            }
        });

        txt_enter_car_madeBy_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_car_madeBy_searchActionPerformed(evt);
            }
        });

        txt_enter_min_seat_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enter_min_seat_searchActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seach car by city:");

        txt_maintenanceexpired.setBackground(new java.awt.Color(51, 51, 51));
        txt_maintenanceexpired.setForeground(new java.awt.Color(255, 255, 255));
        txt_maintenanceexpired.setText("Vehicle Maintenance Unexpired:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollpaneTable))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_enter_min_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_enter_max_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_enter_car_madeBy_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(26, 26, 26)
                                        .addComponent(txt_enter_city_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_maintenanceexpired, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_city_search)
                                    .addComponent(btn_car_made_By_search)
                                    .addComponent(btn_First_availablecar_search)
                                    .addComponent(btn_minmax_seat_search1)
                                    .addComponent(btn_expired_certi_search)
                                    .addComponent(btn_currently_available_or_not_search))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_enter_serial_search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txt_enter_car_name_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btn_manByUber_search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txt_enter_model_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btn_model_search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_enter_man_year_search, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btn_man_year_search, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_table_UpdatedOn_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(502, 502, 502)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 293, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btn_First_availablecar_search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_currently_available_or_not_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_expired_certi_search)
                                    .addComponent(txt_maintenanceexpired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_enter_min_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_enter_max_seat_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_enter_car_madeBy_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_car_made_By_search)))
                            .addComponent(btn_minmax_seat_search1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_enter_city_name_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_city_search))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollpaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btn_man_year_search)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_enter_serial_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_serial_search))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_enter_model_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_model_search))
                                    .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(txt_enter_car_name_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btn_manByUber_search))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_enter_man_year_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_table_UpdatedOn_search1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(lblLastUpdated)))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_table_UpdatedOn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_table_UpdatedOn_search1ActionPerformed
        // TODO add your handling code here:

        // Get Manufaturer
        lblLastUpdated.setText("Today");
    }//GEN-LAST:event_btn_table_UpdatedOn_search1ActionPerformed

    private void txt_enter_man_year_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_man_year_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_man_year_searchActionPerformed

    private void txt_enter_serial_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_serial_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_serial_searchActionPerformed

    private void txt_enter_car_name_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_car_name_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_car_name_search1ActionPerformed

    private void txt_enter_model_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_model_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_model_searchActionPerformed

    private void btn_model_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_model_searchActionPerformed
        // TODO add your handling code here:
        
        //modelnumber 
         ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_model_search.getText();
        for(UberDetails car: allCars){

            if(car.getModel().equals(filterMan)){
                searchList.add(car);
            }
        }

          populateTableByList2(searchList);
        
    }//GEN-LAST:event_btn_model_searchActionPerformed

    private void btn_serial_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serial_searchActionPerformed
        // TODO add your handling code here:
        //serialno.
        
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_serial_search.getText();
        for(UberDetails car: allCars){

            if(car.getSerialno().equals(filterMan)){
                searchList.add(car);
            }
        }

          populateTableByList2(searchList);
        
    }//GEN-LAST:event_btn_serial_searchActionPerformed

    private void btn_manByUber_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manByUber_searchActionPerformed
        // TODO add your handling code here:
        //carmanufactured
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_car_name_search1.getText();
        for(UberDetails car: allCars){

            if(car.getManufacture().equals(filterMan)){
                searchList.add(car);
            }
        }

          populateTableByList2(searchList);
        
                
    }//GEN-LAST:event_btn_manByUber_searchActionPerformed

    private void txt_enter_city_name_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_city_name_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_city_name_searchActionPerformed

    private void btn_city_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_city_searchActionPerformed
        // TODO add your handling code here:

//search for loaction
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_city_name_search.getText();
        for(UberDetails car: allCars){

            if(car.getLocation().equals(filterMan)){
                searchList.add(car);
            }
        }

          populateTableByList2(searchList);
         
        
    }//GEN-LAST:event_btn_city_searchActionPerformed

    private void txt_enter_max_seat_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_max_seat_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_max_seat_searchActionPerformed

    private void btn_car_made_By_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_made_By_searchActionPerformed
        // TODO add your handling code here://search manufacturer details
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_car_madeBy_search.getText();

        for(UberDetails car: allCars){

            //Match the car.getManufacturer with filterMan
           
            if(car.getManufacture().equals(filterMan)){
                searchList.add(car);
            }
        }

        populateTableByList2(searchList);

       
    }//GEN-LAST:event_btn_car_made_By_searchActionPerformed

    private void btn_expired_certi_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expired_certi_searchActionPerformed
        // TODO add your handling code here:
        //listofcarswithexpirecerti
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();
        for(UberDetails car: allCars){
            if(car.isManucerti() == false){
                searchList.add(car);
            }
        }
        
        
        populateTableByList2(searchList);
        
        
        
    }//GEN-LAST:event_btn_expired_certi_searchActionPerformed

    private void btn_First_availablecar_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_First_availablecar_searchActionPerformed
        // TODO add your handling code here:
        
        //FIRSTCARAVAILABLE
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();
        
        for(UberDetails car: allCars){
            if(car.isAvailable() == true){
                searchList.add(car);
                break;
            }
        }
        
        
        populateTableByList2(searchList);
        
        

    }//GEN-LAST:event_btn_First_availablecar_searchActionPerformed

    private void btn_minmax_seat_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minmax_seat_search1ActionPerformed
        // TODO add your handling code here:
        //minmax
        
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();
        
        String filterMan = txt_enter_min_seat_search.getText();
        String filterMan1 = txt_enter_max_seat_search.getText();

        
               
        for(UberDetails car: allCars){
        
            
            //Match the car.getManufacturer with filterMan
            if(car.getMinseats() >= Integer.parseInt(filterMan) && car.getMinseats() < Integer.parseInt(filterMan1)){
                searchList.add(car);
            }
        }
        
        
        populateTableByList2(searchList);
    }//GEN-LAST:event_btn_minmax_seat_search1ActionPerformed

    private void txt_enter_car_madeBy_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_car_madeBy_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_car_madeBy_searchActionPerformed

    private void txt_enter_min_seat_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enter_min_seat_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enter_min_seat_searchActionPerformed

    private void btn_man_year_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_man_year_searchActionPerformed
        // TODO add your handling code here:
        //searchbyyear
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

        String filterMan = txt_enter_man_year_search.getText();

        for(UberDetails car: allCars){

            //Match the car.getManufacturer with filterMan
         
            if((car.getManuyear()+"").equals(filterMan)){
                searchList.add(car);
            }
        }

        populateTableByList2(searchList);
        
    }//GEN-LAST:event_btn_man_year_searchActionPerformed

    private void btn_currently_available_or_not_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_currently_available_or_not_searchActionPerformed
        // TODO add your handling code here:
        //carvavailableornot
        ArrayList<UberDetails> allCars = history.getHistory();
        ArrayList<UberDetails> searchList = new ArrayList<>();

       

        for(UberDetails car: allCars){
            if(car.isAvailable()== true){
                                searchList.add(car);

                     
            }
        }       
        int unavailableCars = allCars.size()-searchList.size();
        
         JOptionPane.showMessageDialog(this, "Total available cars :"+searchList.size()+"  Total unavailable cars :"+unavailableCars);

        populateTableByList2(searchList);
        
        
        

        
        
    }//GEN-LAST:event_btn_currently_available_or_not_searchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_First_availablecar_search;
    private javax.swing.JButton btn_car_made_By_search;
    private javax.swing.JButton btn_city_search;
    private javax.swing.JButton btn_currently_available_or_not_search;
    private javax.swing.JButton btn_expired_certi_search;
    private javax.swing.JButton btn_manByUber_search;
    private javax.swing.JButton btn_man_year_search;
    private javax.swing.JButton btn_minmax_seat_search1;
    private javax.swing.JButton btn_model_search;
    private javax.swing.JButton btn_serial_search;
    private javax.swing.JButton btn_table_UpdatedOn_search1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLastUpdated;
    private javax.swing.JScrollPane scrollpaneTable;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txt_enter_car_madeBy_search;
    private javax.swing.JTextField txt_enter_car_name_search1;
    private javax.swing.JTextField txt_enter_city_name_search;
    private javax.swing.JTextField txt_enter_man_year_search;
    private javax.swing.JTextField txt_enter_max_seat_search;
    private javax.swing.JTextField txt_enter_min_seat_search;
    private javax.swing.JTextField txt_enter_model_search;
    private javax.swing.JTextField txt_enter_serial_search;
    private javax.swing.JTextField txt_maintenanceexpired;
    // End of variables declaration//GEN-END:variables
 
private void  populateTableByList2(ArrayList<UberDetails> list) {
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        model.setRowCount(0);
        
        for(UberDetails ud :list){
            Object[] row=new Object[11];
            row[0]=ud;
            row[1]=ud.getCarname();
            row[2]=ud.getModel();
            row[3]=ud.getManuyear();
            row[4]=ud.getSerialno();
            row[5]=ud.isManucerti();//check whether it should be get or is(as get is not available)
            row[6]=ud.isAvailable();
            row[7]=ud.getLocation();
            row[8]=ud.getMinseats();
            row[9]=ud.getMaxseats();
            row[10]=ud.getTime();
            
            model.addRow(row);
            
        }
        
        
    } 

  
}
