/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.DateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UberDetails;
import model.UberDetailsHistory;
import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author kohli
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    UberDetailsHistory history;
    public ViewJPanel(UberDetailsHistory history) {
        initComponents();
        this.history=history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHead = new javax.swing.JLabel();
        scrollpaneTable = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblManufacture = new javax.swing.JLabel();
        txtManufacture = new javax.swing.JTextField();
        lblCarname = new javax.swing.JLabel();
        txtCarname = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        lblManuyear = new javax.swing.JLabel();
        txtManuyear1 = new javax.swing.JTextField();
        lblSerialno = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        txtMinseats = new javax.swing.JTextField();
        lblMinseats = new javax.swing.JLabel();
        lblAvailabletime = new javax.swing.JLabel();
        txtAvailabletime = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        chkbxAvailYes = new javax.swing.JCheckBox();
        chkbxlExpiredYes = new javax.swing.JCheckBox();
        lblExpired = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblHead.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHead.setForeground(new java.awt.Color(255, 255, 255));
        lblHead.setText("View Car Details");

        tblView.setBackground(new java.awt.Color(153, 153, 153));
        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Manufacturer", "Car Name", "Model", "Manu. Year", "Serial No.", "Vehicle Maint. ", "Availability", "Location", "Seats", "Available Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollpaneTable.setViewportView(tblView);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblManufacture.setForeground(new java.awt.Color(255, 255, 255));
        lblManufacture.setText("Manufacturer:");

        lblCarname.setForeground(new java.awt.Color(255, 255, 255));
        lblCarname.setText("Car Name:");

        lblModel.setForeground(new java.awt.Color(255, 255, 255));
        lblModel.setText("Model:");

        lblManuyear.setForeground(new java.awt.Color(255, 255, 255));
        lblManuyear.setText("Manu. Year:");

        lblSerialno.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialno.setText("Serial No:");

        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location:");

        lblMinseats.setForeground(new java.awt.Color(255, 255, 255));
        lblMinseats.setText("Min. Seats:");

        lblAvailabletime.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailabletime.setText("Available Time(in 24 hrs):");

        lblAvailability.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailability.setText("Availability:");

        chkbxAvailYes.setBackground(new java.awt.Color(51, 51, 51));
        chkbxAvailYes.setForeground(new java.awt.Color(255, 255, 255));
        chkbxAvailYes.setText("YES");

        chkbxlExpiredYes.setBackground(new java.awt.Color(51, 51, 51));
        chkbxlExpiredYes.setForeground(new java.awt.Color(255, 255, 255));
        chkbxlExpiredYes.setText("YES");

        lblExpired.setForeground(new java.awt.Color(255, 255, 255));
        lblExpired.setText("Vehicle Certificate Expired:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollpaneTable, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblExpired)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkbxlExpiredYes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManufacture)
                                    .addComponent(lblModel)
                                    .addComponent(lblCarname)
                                    .addComponent(lblManuyear))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtManuyear1)
                                    .addComponent(txtModel)
                                    .addComponent(txtCarname)
                                    .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvailability, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMinseats, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAvailabletime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerialno, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkbxAvailYes)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtAvailabletime)
                                        .addComponent(txtMinseats)
                                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(29, 29, 29)
                .addComponent(btnUpdate)
                .addGap(66, 66, 66)
                .addComponent(btnDelete)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(lblHead)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnUpdate, btnView});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManufacture)
                            .addComponent(txtManufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCarname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManuyear, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManuyear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkbxlExpiredYes)
                            .addComponent(lblExpired)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvailability)
                            .addComponent(chkbxAvailYes))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMinseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSerialno)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvailabletime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDelete, btnUpdate, btnView});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex=tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        UberDetails selectedDetails =(UberDetails)model.getValueAt(selectedRowIndex,0);
        
        history.deleteDetails(selectedDetails);
        JOptionPane.showMessageDialog(this,"Uber car details deleted");
        
        populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex=tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        UberDetails selectedDetails =(UberDetails)model.getValueAt(selectedRowIndex,0);
        
        txtManufacture.setText(selectedDetails.getManufacture());
        txtCarname.setText(selectedDetails.getCarname());
        txtModel.setText(selectedDetails.getModel());
        txtManuyear1.setText(String.valueOf(selectedDetails.getManuyear()));
        //txtMaxseats.setText(String.valueOf(selectedDetails.getMaxseats()));
        txtMinseats.setText(String.valueOf(selectedDetails.getMinseats()));
        txtSerialNo.setText(selectedDetails.getSerialno());
        txtLocation.setText(selectedDetails.getLocation());
        txtAvailabletime.setText(String.valueOf(selectedDetails.getTime()));
        chkbxAvailYes.setSelected(selectedDetails.isAvailable());
        chkbxlExpiredYes.setSelected(selectedDetails.isManucerti());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         int selectedRowIndex=tblView.getSelectedRow();
        
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to view");
            return;
        }
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        UberDetails selectedDetails =(UberDetails)model.getValueAt(selectedRowIndex,0);
        
        selectedDetails.setManufacture(txtManufacture.getText());
        selectedDetails.setCarname(txtCarname.getText());
        selectedDetails.setModel(txtModel.getText());
        selectedDetails.setManuyear(Integer.parseInt(txtManuyear1.getText()));
        //selectedDetails.setMaxseats(Integer.parseInt(txtMaxseats.getText()));
        selectedDetails.setMinseats(Integer.parseInt(txtMinseats.getText()));
        selectedDetails.setLocation(txtLocation.getText());
        selectedDetails.setSerialno(txtSerialNo.getText());
        selectedDetails.setAvailable(chkbxAvailYes.isSelected());
        selectedDetails.setManucerti(chkbxlExpiredYes.isSelected());
        selectedDetails.setTime(Double.parseDouble(txtAvailabletime.getText()));
        
         //history.setLastupdatedDate(new Date());
      
        
        //txtManufacture.setText(selectedDetails.getManufacture());
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkbxAvailYes;
    private javax.swing.JCheckBox chkbxlExpiredYes;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblAvailabletime;
    private javax.swing.JLabel lblCarname;
    private javax.swing.JLabel lblExpired;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblManufacture;
    private javax.swing.JLabel lblManuyear;
    private javax.swing.JLabel lblMinseats;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialno;
    private javax.swing.JScrollPane scrollpaneTable;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtAvailabletime;
    private javax.swing.JTextField txtCarname;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtManufacture;
    private javax.swing.JTextField txtManuyear1;
    private javax.swing.JTextField txtMinseats;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model=(DefaultTableModel)tblView.getModel();
        model.setRowCount(0);
        
        for(UberDetails ud :history.getHistory()){
            Object[] row=new Object[11];
            row[0]=ud;
            row[1]=ud.getCarname();
            row[2]=ud.getModel();
            row[3]=ud.getManuyear();
            row[4]=ud.getSerialno();
            row[5]=ud.isManucerti();//check whether it should be get or is(as get is not available)
            row[6]=ud.isAvailable();
            row[7]=ud.getLocation();
            row[8]=ud.getMinseats();
            row[9]=ud.getMaxseats();
            row[10]=ud.getTime();
            //txtdateofupdate.setText(DateFormat.getDateTimeInstance().format(history.getLastupdatedDate()));
            System.out.println(row);
            model.addRow(row);
            
        }
        
        
    }
}
