/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Sys;

/**
 *
 * @author kohli
 */
public class AddDetails extends javax.swing.JPanel {

    /**
     * Creates new form AddDetails
     */
    MainJFrame mainjframe;
    Sys sys;
    
    public AddDetails(Sys sys, MainJFrame mainjFrame) {
        initComponents();
        this.sys = sys;
        this.mainjframe = mainjFrame;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAddCommunity = new javax.swing.JRadioButton();
        btnAddHouse = new javax.swing.JRadioButton();
        btnAddPerson = new javax.swing.JRadioButton();
        btnAddEncounter = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));

        btnAddCommunity.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddCommunity);
        btnAddCommunity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddCommunity.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCommunity.setText("Add Community");
        btnAddCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommunityActionPerformed(evt);
            }
        });

        btnAddHouse.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddHouse);
        btnAddHouse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddHouse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddHouse.setText("Add House");
        btnAddHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHouseActionPerformed(evt);
            }
        });

        btnAddPerson.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddPerson);
        btnAddPerson.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPerson.setText("Add Person");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnAddEncounter.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(btnAddEncounter);
        btnAddEncounter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAddEncounter.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEncounter.setText("Add Visit");

        btnSubmit.setBackground(new java.awt.Color(0, 204, 204));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Picture12.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddHouse)
                    .addComponent(btnAddCommunity)
                    .addComponent(btnAddEncounter)
                    .addComponent(btnAddPerson)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSubmit)))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnAddCommunity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddHouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddEncounter)
                .addGap(29, 29, 29)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCommunityActionPerformed

    private void btnAddHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddHouseActionPerformed

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
    if(btnAddCommunity.isSelected()){
         CommunityPanel communitypanel = new CommunityPanel(this.sys, this.mainjframe);
            this.mainjframe.updateRightJPanel(communitypanel);
            
        }
    else if(btnAddHouse.isSelected()){
           HousePanel housepanel = new HousePanel(this.sys, this.mainjframe);
            this.mainjframe.updateRightJPanel(housepanel);
    }
    else if(btnAddPerson.isSelected()){
        Addperson addperson=new Addperson(this.sys,this.mainjframe);
        this.mainjframe.updateRightJPanel(addperson);
    }
    else if(btnAddEncounter.isSelected()){
        Visitencounter visitencounter=new Visitencounter(this.sys, this.mainjframe);
        this.mainjframe.updateRightJPanel(visitencounter);
    }

    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAddCommunity;
    private javax.swing.JRadioButton btnAddEncounter;
    private javax.swing.JRadioButton btnAddHouse;
    private javax.swing.JRadioButton btnAddPerson;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
